global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "agent-api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["agent-api:3000"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]
